
export const DO_REGISTRATION_SUCCESSFULL = 'DO_REGISTRATION_SUCCESSFULL'
export const DO_REGISTRATION_FAILED = 'DO_REGISTRATION_FAILED'

export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS'
export const ON_LOGIN_FAILED = 'ON_LOGIN_FAILED'

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'



