
export const DO_REGISTRATION_SUCCESSFULL = 'DO_REGISTRATION_SUCCESSFULL'
export const DO_REGISTRATION_FAILED = 'DO_REGISTRATION_FAILED'

export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS'
export const ON_LOGIN_FAILED = 'ON_LOGIN_FAILED'

